# Generated by Django 4.1.7 on 2023-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='link',
        ),
        migrations.AddField(
            model_name='character',
            name='href',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
